#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import wifi
import iopb
import threading

#connect to wifi
wifi.main()
#update config from the server
iobj = iopb.iobj()
iobj.update_cfg_from_json()
# iobj.ftp.ftp_disconnect() #close it because will be reopen as anotehr instance in the sync

#start sync script
t1=threading.Thread(target=iobj.auto_sync, daemon=True)
t1.start()

#load pibooth
sys.path.insert(1, '/opt/pibooth')
import pibooth
print('pibooth loaded from', pibooth.__path__)
from pibooth.booth import main
sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
sys.exit(main())
