#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import wifi
import iopb
import threading
import os

#check that the USB is Connected
if not os.path.isdir('/USB/im/'):
    try:
        os.mkdir('/USB/im/')
    except:
        print('Could not initualize the /USB/im/ dir')
# #connect to wifi
# wifi.main()
#check the wifi
local, internet = wifi.check_connection()

#check if need to updated
if internet:
    with open('/opt/pibooth/custom_utils/update', 'r') as f:
        first_line = f.readline().rstrip('\n')
    if first_line == 'yes':
        with open('/opt/pibooth/custom_utils/update', 'w') as f:
            f.write('no\n')
        print('Trying a git update')
        os.system('git --git-dir=/opt/pibooth/.git')

#update config from the server
iobj = iopb.iobj()
iobj.update_cfg_from_json()

#start sync script
t1=threading.Thread(target=iobj.auto_sync, daemon=True)
t1.start()

#load pibooth
sys.path.insert(1, '/opt/pibooth')
import pibooth
print('pibooth loaded from', pibooth.__path__)
from pibooth.booth import main
sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
sys.exit(main())
