#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
sys.path.insert(1, '/opt/pibooth')
import pibooth
import wifi
import io

if __name__ == '__main__':
    #connect to wifi
    wifi.main()
    #update config from the server
    iobj = io.iobj()
    iobj.update_cfg_from_json()

    print(pibooth.__path__)
    from pibooth.booth import main
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
